apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv4
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  storageClassName: "managed-nfs-storage1"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/data/pv4
    server: 192.168.1.209
