apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  storageClassName: "managed-nfs-storage5"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/data/pv5
    server: 192.168.1.209
